# Generated by Django 5.1.5 on 2025-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
