# Generated by Django 5.1.5 on 2025-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.CharField(max_length=100000000000),
        ),
    ]
